# -*- coding: utf-8 -*-
"""ml_assignment2_latest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_9oGDb5ClYLrwtt9ZZLBkh8q8r_t78x
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# files_and_dirs = os.listdir("/content/drive/MyDrive")

# # Print the list
# for item in files_and_dirs:
#     print(item)

data = pd.read_csv("/content/drive/MyDrive/adult.data.csv")

data.replace("?", np.nan, inplace=True)
data.dropna(inplace=True)

label_encoders = {}
for column in data.columns:
    if data[column].dtype == object:
        le = LabelEncoder()
        data[column] = le.fit_transform(data[column])
        label_encoders[column] = le

# num_columns = data.shape[1]
# print(f"Number of columns in the DataFrame: {num_columns}")

# num_rows = y_test.shape[0]
# print(f"Number of rows in the DataFrame: {num_rows}")

X = data.drop("income", axis=1)
y = data["income"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "AUC": roc_auc_score(y_test, y_prob),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }

    joblib.dump(model, f"{name}.pkl")

print("\nModel Evaluation Results:\n")
for model_name, metrics in results.items():
    print(model_name)
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")
    print("-" * 40)

